In [11]:
import numpy as np

In [3]:
import json

In [4]:
import pandas as pd

In [5]:
data = pd.read_json('generated_scores/generated_random_params_big_scores.jsonl', orient='records', lines=True)

In [6]:
data.head()

,dialog,real_answer,predicted_answers,params,change_type,mean_score,std_score
0,"[Wh didn't anyone explain adulting to me, What...",None,"[{'answer': 'I hope so, i would like to be a k...","{'top_p': 1.0, 'top_k': 50, 'typical_p': 0.65,...",typical_p,0.066726,0.110262
1,[It feels great having a girlfriend who puts h...,None,[{'answer': 'It's nice to have someone you can...,"{'top_p': 1.0, 'top_k': 50, 'typical_p': 0.65,...",typical_p,0.521633,0.409304
2,"[I went to the grocery store, while at the cas...",None,"[{'answer': 'Yeah, I'm just really upset about...","{'top_p': 0.7000000000000001, 'top_k': 100, 't...",top_p,0.131869,0.121322
3,[i live next to a football field and every foo...,None,[{'answer': 'It is my right to keep them out o...,"{'top_p': 1.0, 'top_k': 50, 'typical_p': 0.300...",typical_p,0.414262,0.447598
4,"[In 6 days I leave for Peru, Wow! I've never b...",None,"[{'answer': 'Yeah, it's a lot different than t...","{'top_p': 1.0, 'top_k': 50, 'typical_p': 0.700...",typical_p,0.286111,0.150189

In [7]:
data = pd.concat([data.drop(['params'], axis=1), data['params'].apply(pd.Series)], axis=1)

In [8]:
data.head()

,dialog,real_answer,predicted_answers,change_type,mean_score,std_score,top_p,top_k,typical_p,temperature,do_sample
0,"[Wh didn't anyone explain adulting to me, What...",None,"[{'answer': 'I hope so, i would like to be a k...",typical_p,0.066726,0.110262,1.00,50,0.65,0.30,True
1,[It feels great having a girlfriend who puts h...,None,[{'answer': 'It's nice to have someone you can...,typical_p,0.521633,0.409304,1.00,50,0.65,0.75,True
2,"[I went to the grocery store, while at the cas...",None,"[{'answer': 'Yeah, I'm just really upset about...",top_p,0.131869,0.121322,0.70,100,1.00,0.45,True
3,[i live next to a football field and every foo...,None,[{'answer': 'It is my right to keep them out o...,typical_p,0.414262,0.447598,1.00,50,0.30,1.15,True
4,"[In 6 days I leave for Peru, Wow! I've never b...",None,"[{'answer': 'Yeah, it's a lot different than t...",typical_p,0.286111,0.150189,1.00,50,0.70,0.25,True
5,"[I almost stepped on a snake today, Did the sn...",None,[{'answer': 'Not that I know of. But this one ...,top_p,0.179698,0.140257,0.85,100,1.00,0.75,True
6,[I think my daughter is going to always like s...,None,[{'answer': 'I hope so. it would be nice for h...,both,0.284501,0.349830,0.85,250,0.70,0.85,True
7,"[My girlfriend just left me, this is awful, Th...",None,"[{'answer': 'Yeah, I think I can do that. Than...",typical_p,0.373261,0.261553,1.00,50,0.40,1.00,True
8,[I kept all of my kids first day pics every ye...,None,"[{'answer': 'That is nice you went for a run, ...",typical_p,0.279924,0.378386,1.00,50,0.25,1.15,True
9,[Feeling strange about payday. It is a stressf...,None,[{'answer': 'It's hard to see someone you care...,typical_p,0.966226,0.000000,1.00,50,0.05,0.20,True

In [9]:
data = data.round({'top_p': 2, 'typical_p': 2, 'temperature': 2})

In [12]:
top_k_range = [5, 25, 50, 75, 100, 150, 250, 350, 500, 750, 1000]

top_p_range = np.arange(0.05, 1.01, 0.05)

typical_p_range = top_p_range

temperature_range = np.arange(0.05, 1.21, 0.05)

change_type_range = ['top_p', 'typical_p', 'both']

In [13]:
change_type_vocab = {'top_p': 0, 'typical_p': 1, 'both': 2}
top_p_vocab = {round(value, 2): i for value, i in zip(top_p_range, range(len(top_p_range)))}
typical_p_vocab = {round(value, 2): i for value, i in zip(typical_p_range, range(len(typical_p_range)))}
top_k_vocab = {round(value, 2): i for value, i in zip(top_k_range, range(len(top_k_range)))}
temperature_vocab = {round(value, 2): i for value, i in zip(temperature_range, range(len(temperature_range)))}

In [15]:
data['change_type'] = data['change_type'].map(change_type_vocab)
data['top_p'] = data['top_p'].map(top_p_vocab)
data['top_k'] = data['top_k'].map(top_k_vocab)
data['typical_p'] = data['typical_p'].map(typical_p_vocab)
data['temperature'] = data['temperature'].map(temperature_vocab)

In [16]:
data.head()

,dialog,real_answer,predicted_answers,change_type,mean_score,std_score,top_p,top_k,typical_p,temperature,do_sample
0,"[Wh didn't anyone explain adulting to me, What...",None,"[{'answer': 'I hope so, i would like to be a k...",1,0.066726,0.110262,19,2,12,5,True
1,[It feels great having a girlfriend who puts h...,None,[{'answer': 'It's nice to have someone you can...,1,0.521633,0.409304,19,2,12,14,True
2,"[I went to the grocery store, while at the cas...",None,"[{'answer': 'Yeah, I'm just really upset about...",0,0.131869,0.121322,13,4,19,8,True
3,[i live next to a football field and every foo...,None,[{'answer': 'It is my right to keep them out o...,1,0.414262,0.447598,19,2,5,22,True
4,"[In 6 days I leave for Peru, Wow! I've never b...",None,"[{'answer': 'Yeah, it's a lot different than t...",1,0.286111,0.150189,19,2,13,4,True

In [17]:
columns = ['top_p', 'top_k', 'typical_p', 'temperature', 'do_sample']
data['params'] = data[columns].to_dict(orient='records')

In [18]:
data = data.drop(columns=columns)

In [19]:
data['number_of_answers'] = data['predicted_answers'].apply(lambda x: len(set([ans["answer"] for ans in x])))

In [35]:
data_good = data[(data.mean_score >= data.mean_score.quantile(0.5)) & (data.number_of_answers >= 3) & (data.std_score >= 0.03)]

In [36]:
len(data_good)/len(data)

0.2716012084592145

In [37]:
len(data_good)

10788

In [31]:
data_good[['dialog', 'real_answer', 'predicted_answers', 'params', 'mean_score', 'std_score', 'change_type', 'number_of_answers']].to_json('generated_scores/final_big_embedded_good.jsonl', orient='records', lines=True)